### ISSUE TITLE
SeYeol00

### ISSUE THREAD

**Issue by SeYeol00** [Programming-Seungwan/ALGORITHM_STUDY_PRIVATE#1]
코딩 테스트 대비는 어떤 점을 위주로 하나요

**Comment by Programming-Seungwan** [comment]
최근 문제들은 대부분 dfs, bfs 같은 탐색과 다익스트라, 크루스칼 같은 길 찾기, dp와 그리디 정도로 이론은 한정되는 거 같고... 이것들을 조합해서 "구현"에 가깝게 내는 거 같아요.

그래서 백준에서 기본적으로 한 골드 4까지 풀고 그 다음은 프로그래머스 기업 기출 위주로 하는 중...!

**Comment by SeYeol00** [comment]
감사합니다. 이런 알고리즘들을 합쳐서 구현한다면 과거에 비해 대폭 난이도가 상승했네요 ㅠㅠ 점점 걱정이 됩니다.
